name: mokumo_analytics
version: '0.1.0'

profile: mokumo

model-paths: ['models']
analysis-paths: ['analyses']
test-paths: ['tests']
seed-paths: ['seeds']
macro-paths: ['macros']
snapshot-paths: ['snapshots']

clean-targets:
  - target
  - dbt_packages

models:
  mokumo_analytics:
    staging:
      +materialized: view
      +schema: staging
    intermediate:
      +materialized: ephemeral
      +schema: intermediate
    marts:
      +materialized: table
      +schema: marts

dispatch:
  - macro_namespace: dbt_project_evaluator
    search_order: ['mokumo_analytics', 'dbt_project_evaluator']

snapshots:
  +target_schema: snapshots
