//! `scorecard` — sticky PR scorecard schema and producer surface.
//!
//! The crate owns the typed wire format for the sticky PR scorecard comment
//! that mokumo posts on every pull request. It is consumed in two places:
//!
//! - The CI **producer** (`bin/aggregate`) constructs typed `Row` values from
//!   gate outputs and serializes the resulting `Scorecard` to `scorecard.json`
//!   for the renderer.
//! - The CI **renderer** (Node.js step in `.github/workflows/scorecard-comment.yml`)
//!   reads the artifact, validates it against the committed
//!   `.config/scorecard/schema.json`, and posts/updates the sticky comment.
//!
//! See `decisions/mokumo/adr-scorecard-crate-shape.md` for the architectural
//! rationale (single crate per the four-forcing-functions framework, lib
//! mokumo-deps-zero, three layers of `failure_detail_md` enforcement).
//!
//! # Layer 1 typestate
//!
//! `Row` and each variant are marked `#[non_exhaustive]`, so external
//! callers cannot struct-literal a `Row` and cannot match it without a
//! wildcard arm. They must construct via the methods on `Row`
//! ([`Row::coverage_delta_red`], [`Row::coverage_delta_green`],
//! [`Row::coverage_delta_yellow`]). The constructors mint `Status`
//! internally so external callers cannot supply a wrong status. The Red
//! constructor takes `failure_detail_md: String` (not `Option<String>`),
//! making "Red row without inline detail" a compile-time impossibility for
//! external callers.
//!
//! Verified by the trybuild UI tests at `tests/trybuild/`.

#![forbid(unsafe_code)]

use schemars::JsonSchema;
use serde::{Deserialize, Serialize};

pub mod emit_schema;
pub mod schema_postprocess;
pub mod threshold;

#[cfg(feature = "cli")]
pub mod aggregate;

/// Top-level scorecard artifact.
///
/// Serializes as `scorecard.json` and is the trust boundary for the
/// renderer. The committed JSON Schema at `.config/scorecard/schema.json`
/// (regenerated by the `emit-schema` binary) is the validator's contract.
#[derive(Debug, Clone, Serialize, Deserialize, JsonSchema)]
pub struct Scorecard {
    /// Schema version. Future row variants bump per the migration playbook
    /// in `decisions/mokumo/adr-scorecard-crate-shape.md`.
    pub schema_version: u32,

    /// Pull request metadata captured at producer time so the renderer can
    /// render without a separate `pr-meta.json` lookup.
    pub pr: PrMeta,

    /// Resolved status across all rows. The renderer's banner reads this
    /// directly; per the .feature spec the banner status is the worst
    /// status across all rows.
    pub overall_status: Status,

    /// Scorecard rows.
    pub rows: Vec<Row>,

    /// Top-failing gate Check Run links (max three per the two-click rule).
    /// May be omitted on the wire; deserialization fills `vec![]`.
    /// Producers SHOULD emit explicitly so the wire contract is
    /// unambiguous.
    #[serde(default)]
    pub top_failures: Vec<GateRun>,

    /// External link to the full Check Runs page on the head commit, so
    /// the comment can satisfy "every failing gate is one click away" even
    /// when more than three gates fail.
    pub all_check_runs_url: String,

    /// `true` when the producer resolved row statuses using the
    /// hardcoded [`threshold::ThresholdConfig::fallback`] thresholds
    /// (no operator `quality.toml` was present or readable). The
    /// renderer keys off this flag to emit
    /// [`threshold::STARTER_PREAMBLE`] +
    /// [`threshold::FALLBACK_MARKER`] + [`threshold::PATH_HINT_COMMENT`]
    /// so operators can tell at a glance that the verdict came from
    /// starter-wheel defaults rather than their tuned thresholds.
    pub fallback_thresholds_active: bool,
}

/// GitHub PR number. Newtype rather than `u64` so a method that wants
/// "the PR number" cannot accept a raw `RunId`, and a future migration
/// (e.g. recording the PR by node id rather than number) is a single
/// type-system change instead of a sweep across renderer + producer
/// surfaces. Transparent on the wire and in the JSON Schema, so the
/// renderer reads it as a plain integer.
#[derive(Debug, Clone, Copy, PartialEq, Eq, Hash, Serialize, Deserialize, JsonSchema)]
#[serde(transparent)]
#[schemars(transparent)]
pub struct PrNumber(pub u64);

impl From<u64> for PrNumber {
    fn from(n: u64) -> Self {
        Self(n)
    }
}

/// GitHub Check Run id. Same rationale as [`PrNumber`].
#[derive(Debug, Clone, Copy, PartialEq, Eq, Hash, Serialize, Deserialize, JsonSchema)]
#[serde(transparent)]
#[schemars(transparent)]
pub struct RunId(pub u64);

impl From<u64> for RunId {
    fn from(n: u64) -> Self {
        Self(n)
    }
}

/// Stable scorecard row id. A short slug (e.g. `"coverage"`,
/// `"mutation"`) used as the renderer's anchor key. Newtype so a
/// `String` parameter can't accidentally land in the `id` slot, and
/// constructors that accept `impl Into<RowId>` get the ergonomics of
/// raw string literals at call sites.
#[derive(Debug, Clone, PartialEq, Eq, Hash, Serialize, Deserialize, JsonSchema)]
#[serde(transparent)]
#[schemars(transparent)]
pub struct RowId(pub String);

impl From<&str> for RowId {
    fn from(s: &str) -> Self {
        Self(s.to_owned())
    }
}

impl From<String> for RowId {
    fn from(s: String) -> Self {
        Self(s)
    }
}

/// Pull request metadata — the renderer's identity for the sticky comment.
#[derive(Debug, Clone, Serialize, Deserialize, JsonSchema)]
pub struct PrMeta {
    pub pr_number: PrNumber,
    pub head_sha: String,
    pub base_sha: String,
    /// Whether the PR was opened from a fork. Renderer uses this to scope
    /// Check Run links against the fork's head commit per the .feature spec.
    pub is_fork: bool,
}

/// Status icon shown on the banner and per-row.
///
/// String-tagged so JSON Schema post-processors can match against
/// `{ "const": "Red" }` to require `failure_detail_md` on Red rows.
#[derive(Debug, Clone, Copy, PartialEq, Eq, Serialize, Deserialize, JsonSchema)]
#[serde(rename_all = "PascalCase")]
pub enum Status {
    Green,
    Yellow,
    Red,
}

/// Fields common to every `Row` variant.
///
/// Pulled out so adding a new variant is a one-line addition to the `Row`
/// enum plus a constructor pair. `Status` deliberately does NOT live here
/// — it is minted by each `Row` constructor so external callers cannot
/// supply a wrong status that disagrees with the constructor name.
#[derive(Debug, Clone, Serialize, Deserialize, JsonSchema)]
pub struct RowCommon {
    /// Stable row id (e.g. `"coverage"`). Used by the renderer for anchors.
    pub id: RowId,
    /// Human-readable label (e.g. `"Coverage"`).
    pub label: String,
    /// Anchor fragment for jump-linking from the comment.
    pub anchor: String,
}

/// Tagged-union of scorecard row variants.
///
/// `#[serde(tag = "type")]` lands in the JSON Schema as a `oneOf` with
/// per-variant `type` constants, which the Layer 2 post-processor walks to
/// inject the `failure_detail_md` invariant.
///
/// `#[non_exhaustive]` on both the enum and each variant blocks external
/// crates from struct-literal construction (variant-level) and from
/// non-wildcard pattern matches (enum-level). Within this crate, both
/// remain reachable so the producer binary can construct rows and the
/// renderer-side dest types can match exhaustively.
#[derive(Debug, Clone, Serialize, Deserialize, JsonSchema)]
#[serde(tag = "type")]
#[non_exhaustive]
pub enum Row {
    /// Code coverage delta vs. base.
    #[non_exhaustive]
    CoverageDelta {
        #[serde(flatten)]
        common: RowCommon,
        /// Resolved status (Green/Yellow/Red). Set by the constructor —
        /// callers cannot supply this directly because `Row::CoverageDelta`
        /// is `#[non_exhaustive]`.
        status: Status,
        /// Raw coverage delta in percentage points vs. the base
        /// branch. The constructor records this alongside the
        /// status that was minted from it; the renderer keeps using
        /// `delta_text` for display, but downstream tooling (and
        /// future trend dashboards) can read `delta_pp` without
        /// reparsing the formatted string.
        delta_pp: f64,
        /// Display string for the delta (e.g. `"+0.3 pp"` or `"-4.2 pp"`).
        delta_text: String,
        /// Inline failure detail rendered below the row when status is Red.
        /// JSON Schema requires this when `status == "Red"`; the Red
        /// constructor enforces the same invariant at compile time for
        /// external callers.
        #[serde(skip_serializing_if = "Option::is_none")]
        failure_detail_md: Option<String>,
    },
}

impl Row {
    /// Construct a Green `CoverageDelta` row. No `failure_detail_md`
    /// because the row is not Red. Status is minted internally.
    pub fn coverage_delta_green(common: RowCommon, delta_pp: f64, delta_text: String) -> Self {
        Row::CoverageDelta {
            common,
            status: Status::Green,
            delta_pp,
            delta_text,
            failure_detail_md: None,
        }
    }

    /// Construct a Yellow `CoverageDelta` row. No `failure_detail_md`
    /// because the row is not Red. Yellow surfaces as a regression but
    /// not a hard failure per the empty-quality.toml fallback rule.
    /// Status is minted internally.
    pub fn coverage_delta_yellow(common: RowCommon, delta_pp: f64, delta_text: String) -> Self {
        Row::CoverageDelta {
            common,
            status: Status::Yellow,
            delta_pp,
            delta_text,
            failure_detail_md: None,
        }
    }

    /// Construct a Red `CoverageDelta` row. The `failure_detail_md`
    /// parameter is required, not `Option<String>` — Layer 1 typestate
    /// makes "Red row without inline detail" a compile-time impossibility
    /// for external callers (combined with `#[non_exhaustive]` on the
    /// variant which blocks struct-literal construction). Status is minted
    /// internally; callers cannot supply a wrong status.
    pub fn coverage_delta_red(
        common: RowCommon,
        delta_pp: f64,
        delta_text: String,
        failure_detail_md: String,
    ) -> Self {
        Row::CoverageDelta {
            common,
            status: Status::Red,
            delta_pp,
            delta_text,
            failure_detail_md: Some(failure_detail_md),
        }
    }
}

/// Reference to a single failing gate's Check Run, surfaced in
/// `top_failures` for the two-click rule.
#[derive(Debug, Clone, Serialize, Deserialize, JsonSchema)]
pub struct GateRun {
    pub gate_name: String,
    pub run_id: RunId,
    /// Absolute https:// URL to the Check Run page.
    pub url: String,
}

#[cfg(test)]
mod tests {
    use super::*;

    fn common() -> RowCommon {
        RowCommon {
            id: "coverage".into(),
            label: "Coverage".into(),
            anchor: "coverage".into(),
        }
    }

    #[test]
    fn red_constructor_sets_status_and_failure_detail() {
        let row = Row::coverage_delta_red(common(), -4.2, "-4.2 pp".into(), "detail".into());
        let Row::CoverageDelta {
            status,
            delta_pp,
            failure_detail_md,
            ..
        } = row;
        assert_eq!(status, Status::Red);
        assert_eq!(delta_pp, -4.2);
        assert_eq!(failure_detail_md.as_deref(), Some("detail"));
    }

    #[test]
    fn green_constructor_sets_status_and_omits_failure_detail() {
        let row = Row::coverage_delta_green(common(), 0.3, "+0.3 pp".into());
        let Row::CoverageDelta {
            status,
            delta_pp,
            failure_detail_md,
            ..
        } = row;
        assert_eq!(status, Status::Green);
        assert_eq!(delta_pp, 0.3);
        assert!(failure_detail_md.is_none());
    }

    #[test]
    fn yellow_constructor_sets_status_and_omits_failure_detail() {
        let row = Row::coverage_delta_yellow(common(), -0.6, "-0.6 pp".into());
        let Row::CoverageDelta {
            status,
            delta_pp,
            failure_detail_md,
            ..
        } = row;
        assert_eq!(status, Status::Yellow);
        assert_eq!(delta_pp, -0.6);
        assert!(failure_detail_md.is_none());
    }

    #[test]
    fn scorecard_round_trips_with_fallback_thresholds_active_flag() {
        let sc = Scorecard {
            schema_version: 0,
            pr: PrMeta {
                pr_number: 1.into(),
                head_sha: "deadbeef".into(),
                base_sha: "cafefeed".into(),
                is_fork: false,
            },
            overall_status: Status::Yellow,
            rows: vec![Row::coverage_delta_yellow(common(), -2.5, "-2.5 pp".into())],
            top_failures: Vec::new(),
            all_check_runs_url: "https://example.test/x/checks".into(),
            fallback_thresholds_active: true,
        };
        let json = serde_json::to_string(&sc).expect("serialize");
        let parsed: Scorecard = serde_json::from_str(&json).expect("round-trip");
        assert!(parsed.fallback_thresholds_active);
    }
}
