//! `scorecard` — sticky PR scorecard schema and producer surface.
//!
//! This crate owns the typed wire format for the sticky PR scorecard comment
//! posted on every mokumo pull request. It is consumed in two places:
//!
//! - The CI **producer** (`bin/aggregate`, V1 PR2) constructs typed `Row`
//!   values from gate outputs and serializes the resulting `Scorecard` to
//!   `scorecard.json` for the renderer.
//! - The CI **renderer** (Node.js step in `.github/workflows/scorecard-comment.yml`,
//!   also V1 PR2) reads the artifact, validates it against the committed
//!   `.config/scorecard/schema.json`, and posts/updates the sticky comment.
//!
//! See `decisions/mokumo/adr-scorecard-crate-shape.md` for the architectural
//! rationale (single crate per the four-forcing-functions framework, lib
//! mokumo-deps-zero, three layers of `failure_detail_md` enforcement).
//!
//! # Layer 1 typestate
//!
//! `Row` is a tagged-union enum (one variant per scorecard row type). Each
//! variant has constructors keyed on the `Status` value: e.g.
//! [`Row::coverage_delta_red`] requires a `failure_detail_md: String`
//! parameter and [`Row::coverage_delta_green`] does not. There is no public
//! way to construct a `Red` row without `failure_detail_md`. This is verified
//! by the trybuild UI tests at `tests/trybuild/`.
//!
//! V1 ships with one `Row` variant (`CoverageDelta`); V4 will fan out to all
//! eight scorecard rows. The constructor pattern is deliberately repeated
//! per-variant so adding a new row type is a self-contained edit.

#![forbid(unsafe_code)]

use schemars::JsonSchema;
use serde::{Deserialize, Serialize};

pub mod threshold;

/// Top-level scorecard artifact.
///
/// Serializes as `scorecard.json` and is the trust boundary for the
/// renderer. The committed JSON Schema at `.config/scorecard/schema.json`
/// (regenerated by the `emit-schema` binary) is the validator's contract.
#[derive(Debug, Clone, Serialize, Deserialize, JsonSchema)]
pub struct Scorecard {
    /// Schema version. v0 ships at `1`; future row variants bump per the
    /// migration playbook in `decisions/mokumo/adr-scorecard-crate-shape.md`.
    pub schema_version: u32,

    /// Pull request metadata captured at producer time so the renderer can
    /// render without a separate `pr-meta.json` lookup.
    pub pr: PrMeta,

    /// Resolved status across all rows. The renderer's banner reads this
    /// directly; per the .feature spec the banner status is the worst
    /// status across all rows.
    pub overall_status: Status,

    /// Scorecard rows. V1 has one (`CoverageDelta`); V4 has all eight.
    pub rows: Vec<Row>,

    /// Top-failing gate Check Run links (max three per the two-click rule).
    /// Present even when empty so the renderer can render a stable shape.
    #[serde(default)]
    pub top_failures: Vec<GateRun>,

    /// External link to the full Check Runs page on the head commit, so
    /// the comment can satisfy "every failing gate is one click away" even
    /// when more than three gates fail.
    pub all_check_runs_url: String,
}

/// Pull request metadata — the renderer's identity for the sticky comment.
#[derive(Debug, Clone, Serialize, Deserialize, JsonSchema)]
pub struct PrMeta {
    pub pr_number: u64,
    pub head_sha: String,
    pub base_sha: String,
    /// Whether the PR was opened from a fork. Renderer uses this to scope
    /// Check Run links against the fork's head commit per the .feature spec.
    pub is_fork: bool,
}

/// Status icon shown on the banner and per-row.
///
/// String-tagged so the Layer 2 JSON Schema `if/then` post-processing
/// (in `bin/emit-schema.rs`) can match against `{ "const": "Red" }` to
/// require `failure_detail_md` on Red rows.
#[derive(Debug, Clone, Copy, PartialEq, Eq, Serialize, Deserialize, JsonSchema)]
#[serde(rename_all = "PascalCase")]
pub enum Status {
    Green,
    Yellow,
    Red,
}

/// Fields common to every `Row` variant. Pulled out so adding a new variant
/// is a one-line addition to the `Row` enum plus a constructor pair.
#[derive(Debug, Clone, Serialize, Deserialize, JsonSchema)]
pub struct RowCommon {
    /// Stable row id (e.g. `"coverage"`). Used by the renderer for anchors.
    pub id: String,
    /// Human-readable label (e.g. `"Coverage"`).
    pub label: String,
    /// Resolved status (Green/Yellow/Red). The producer computes this from
    /// raw values + `quality.toml` thresholds per ADR §"Threshold resolution
    /// lives in the producer".
    pub status: Status,
    /// Anchor fragment for jump-linking from the comment.
    pub anchor: String,
}

/// Tagged-union of scorecard row variants.
///
/// V1 ships with `CoverageDelta` only; V4 expands to all eight variants.
/// The `#[serde(tag = "type")]` discriminator lands in the JSON Schema
/// as a `oneOf` with per-variant `type` constants, which the Layer 2
/// post-processor walks to inject the `failure_detail_md` invariant.
#[derive(Debug, Clone, Serialize, Deserialize, JsonSchema)]
#[serde(tag = "type")]
pub enum Row {
    /// Code coverage delta vs. base. V1 stub variant.
    CoverageDelta {
        #[serde(flatten)]
        common: RowCommon,
        /// Display string for the delta (e.g. `"+0.3 pp"` or `"-4.2 pp"`).
        delta_text: String,
        /// Inline failure detail rendered below the row when status is Red.
        /// Layer 2 JSON Schema requires this when `status == "Red"`.
        /// Layer 1 constructors enforce the same invariant at compile time.
        #[serde(skip_serializing_if = "Option::is_none")]
        failure_detail_md: Option<String>,
    },
}

impl Row {
    /// Construct a Green `CoverageDelta` row. No `failure_detail_md`
    /// because the row is not Red.
    pub fn coverage_delta_green(common: RowCommon, delta_text: String) -> Self {
        debug_assert_eq!(
            common.status,
            Status::Green,
            "use coverage_delta_red for Red rows"
        );
        Row::CoverageDelta {
            common,
            delta_text,
            failure_detail_md: None,
        }
    }

    /// Construct a Yellow `CoverageDelta` row. No `failure_detail_md`
    /// because the row is not Red. Yellow surfaces as a regression but
    /// not a hard failure per the empty-quality.toml fallback rule.
    pub fn coverage_delta_yellow(common: RowCommon, delta_text: String) -> Self {
        debug_assert_eq!(
            common.status,
            Status::Yellow,
            "use coverage_delta_red for Red rows"
        );
        Row::CoverageDelta {
            common,
            delta_text,
            failure_detail_md: None,
        }
    }

    /// Construct a Red `CoverageDelta` row. The `failure_detail_md`
    /// parameter is required, not `Option<String>` — Layer 1 typestate
    /// makes "Red row without inline detail" a compile-time impossibility.
    pub fn coverage_delta_red(
        common: RowCommon,
        delta_text: String,
        failure_detail_md: String,
    ) -> Self {
        debug_assert_eq!(
            common.status,
            Status::Red,
            "use coverage_delta_green/yellow for non-Red rows"
        );
        Row::CoverageDelta {
            common,
            delta_text,
            failure_detail_md: Some(failure_detail_md),
        }
    }
}

/// Reference to a single failing gate's Check Run, surfaced in
/// `top_failures` for the two-click rule.
#[derive(Debug, Clone, Serialize, Deserialize, JsonSchema)]
pub struct GateRun {
    pub gate_name: String,
    pub run_id: u64,
    /// Absolute https:// URL to the Check Run page.
    pub url: String,
}
