/* eslint-disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

/**
 * Status icon shown on the banner and per-row.
 *
 * String-tagged so JSON Schema post-processors can match against `{ "const": "Red" }` to require `failure_detail_md` on Red rows.
 */
export type Status = "Green" | "Yellow" | "Red";
/**
 * Tagged-union of scorecard row variants.
 *
 * `#[serde(tag = "type")]` lands in the JSON Schema as a `oneOf` with per-variant `type` constants, which the Layer 2 post-processor walks to inject the `failure_detail_md` invariant.
 *
 * `#[non_exhaustive]` on both the enum and each variant blocks external crates from struct-literal construction (variant-level) and from non-wildcard pattern matches (enum-level). Within this crate, both remain reachable so the producer binary can construct rows and the renderer-side dest types can match exhaustively.
 */
export type Row = {
  /**
   * Anchor fragment for jump-linking from the comment.
   */
  anchor: string;
  /**
   * Raw coverage delta in percentage points vs. the base branch. The constructor records this alongside the status that was minted from it; the renderer keeps using `delta_text` for display, but downstream tooling (and future trend dashboards) can read `delta_pp` without reparsing the formatted string.
   */
  delta_pp: number;
  /**
   * Display string for the delta (e.g. `"+0.3 pp"` or `"-4.2 pp"`).
   */
  delta_text: string;
  /**
   * Inline failure detail rendered below the row when status is Red. JSON Schema requires this when `status == "Red"`; the Red constructor enforces the same invariant at compile time for external callers.
   */
  failure_detail_md?: string | null;
  /**
   * Stable row id (e.g. `"coverage"`). Used by the renderer for anchors.
   */
  id: string;
  /**
   * Human-readable label (e.g. `"Coverage"`).
   */
  label: string;
  /**
   * Resolved status (Green/Yellow/Red). Set by the constructor — callers cannot supply this directly because `Row::CoverageDelta` is `#[non_exhaustive]`.
   */
  status: Status;
  type: "CoverageDelta";
  [k: string]: unknown;
};

/**
 * Top-level scorecard artifact.
 *
 * Serializes as `scorecard.json` and is the trust boundary for the renderer. The committed JSON Schema at `.config/scorecard/schema.json` (regenerated by the `emit-schema` binary) is the validator's contract.
 */
export interface Scorecard {
  /**
   * External link to the full Check Runs page on the head commit, so the comment can satisfy "every failing gate is one click away" even when more than three gates fail.
   */
  all_check_runs_url: string;
  /**
   * `true` when the producer resolved row statuses using the hardcoded [`threshold::ThresholdConfig::fallback`] thresholds (no operator `quality.toml` was present or readable). The renderer keys off this flag to emit [`threshold::STARTER_PREAMBLE`] + [`threshold::FALLBACK_MARKER`] + [`threshold::PATH_HINT_COMMENT`] so operators can tell at a glance that the verdict came from starter-wheel defaults rather than their tuned thresholds.
   */
  fallback_thresholds_active: boolean;
  /**
   * Resolved status across all rows. The renderer's banner reads this directly; per the .feature spec the banner status is the worst status across all rows.
   */
  overall_status: Status;
  /**
   * Pull request metadata captured at producer time so the renderer can render without a separate `pr-meta.json` lookup.
   */
  pr: PrMeta;
  /**
   * Scorecard rows.
   */
  rows: Row[];
  /**
   * Schema version. Future row variants bump per the migration playbook in `decisions/mokumo/adr-scorecard-crate-shape.md`.
   */
  schema_version: number;
  /**
   * Top-failing gate Check Run links (max three per the two-click rule). May be omitted on the wire; deserialization fills `vec![]`. Producers SHOULD emit explicitly so the wire contract is unambiguous.
   */
  top_failures?: GateRun[];
  [k: string]: unknown;
}
/**
 * Pull request metadata — the renderer's identity for the sticky comment.
 */
export interface PrMeta {
  base_sha: string;
  head_sha: string;
  /**
   * Whether the PR was opened from a fork. Renderer uses this to scope Check Run links against the fork's head commit per the .feature spec.
   */
  is_fork: boolean;
  pr_number: number;
  [k: string]: unknown;
}
/**
 * Reference to a single failing gate's Check Run, surfaced in `top_failures` for the two-click rule.
 */
export interface GateRun {
  gate_name: string;
  run_id: number;
  /**
   * Absolute https:// URL to the Check Run page.
   */
  url: string;
  [k: string]: unknown;
}
