/* eslint-disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

/**
 * Status icon shown on the banner and per-row.
 *
 * String-tagged so JSON Schema post-processors can match against `{ "const": "Red" }` to require `failure_detail_md` on Red rows.
 */
export type Status = "Green" | "Yellow" | "Red";
/**
 * Tagged-union of scorecard row variants.
 *
 * `#[serde(tag = "type")]` lands in the JSON Schema as a `oneOf` with per-variant `type` constants, which the Layer 2 post-processor walks to inject the `failure_detail_md` invariant.
 *
 * `#[non_exhaustive]` on both the enum and each variant blocks external crates from struct-literal construction (variant-level) and from non-wildcard pattern matches (enum-level). Within this crate, both remain reachable so the producer binary can construct rows and the renderer-side dest types can match exhaustively.
 *
 * Every variant carries a `failure_detail_md: Option<String>` so the generic Layer 2 post-processor in `schema_postprocess.rs` can inject the `if status == Red then failure_detail_md required` invariant uniformly across the `oneOf`.
 */
export type Row =
  | {
      /**
       * Anchor fragment for jump-linking from the comment.
       */
      anchor: string;
      /**
       * Per-crate (and eventually per-handler-branch) drill-down. V4 emits an empty default when no per-crate signal is wired upstream; the renderer surfaces a `(per-handler producer pending — see #583)` note inline when `by_crate[].handlers` is empty.
       */
      breakouts?: Breakouts;
      /**
       * Raw coverage delta in percentage points vs. the base branch. The constructor records this alongside the status that was minted from it; the renderer keeps using `delta_text` for display, but downstream tooling (and future trend dashboards) can read `delta_pp` without reparsing the formatted string.
       */
      delta_pp: number;
      /**
       * Display string for the delta (e.g. `"+0.3 pp"` or `"-4.2 pp"`).
       */
      delta_text: string;
      /**
       * Inline failure detail rendered below the row when status is Red. JSON Schema requires this when `status == "Red"`; the Red constructor enforces the same invariant at compile time for external callers.
       */
      failure_detail_md?: string | null;
      /**
       * Stable row id (e.g. `"coverage"`). Used by the renderer for anchors.
       */
      id: string;
      /**
       * Human-readable label (e.g. `"Coverage"`).
       */
      label: string;
      /**
       * Resolved status (Green/Yellow/Red). Set by the constructor — callers cannot supply this directly because `Row::CoverageDelta` is `#[non_exhaustive]`.
       */
      status: Status;
      type: "CoverageDelta";
      [k: string]: unknown;
    }
  | {
      /**
       * Anchor fragment for jump-linking from the comment.
       */
      anchor: string;
      /**
       * Signed delta vs. baseline (positive = new violations landed). Mirrors `CoverageDelta::delta_pp`'s sign discipline.
       */
      delta_count: number;
      /**
       * Producer-rendered display string (e.g. `"5 → 7 (+2)"`).
       */
      delta_text: string;
      failure_detail_md?: string | null;
      /**
       * Stable row id (e.g. `"coverage"`). Used by the renderer for anchors.
       */
      id: string;
      /**
       * Human-readable label (e.g. `"Coverage"`).
       */
      label: string;
      status: Status;
      /**
       * CRAP threshold in effect on this run (default 15). Metric- intrinsic; surfaced so downstream tooling can interpret `delta_count` without out-of-band knowledge.
       */
      threshold: number;
      type: "CrapDelta";
      [k: string]: unknown;
    }
  | {
      /**
       * Anchor fragment for jump-linking from the comment.
       */
      anchor: string;
      delta_text: string;
      failure_detail_md?: string | null;
      /**
       * Stable row id (e.g. `"coverage"`). Used by the renderer for anchors.
       */
      id: string;
      /**
       * Human-readable label (e.g. `"Coverage"`).
       */
      label: string;
      status: Status;
      /**
       * Total surviving mutants for the diff (top-N is the renderer's drill-down; this is the headline count).
       */
      survivor_count: number;
      /**
       * Up to three top survivors selected by the producer.
       */
      top_survivors: MutationSurvivor[];
      type: "MutationSurvivors";
      [k: string]: unknown;
    }
  | {
      /**
       * Anchor fragment for jump-linking from the comment.
       */
      anchor: string;
      /**
       * Per-crate × per-tag breakdown for the renderer's drill-down.
       */
      breakouts: BddCrateBreakout[];
      delta_text: string;
      failure_detail_md?: string | null;
      /**
       * Stable row id (e.g. `"coverage"`). Used by the renderer for anchors.
       */
      id: string;
      /**
       * Human-readable label (e.g. `"Coverage"`).
       */
      label: string;
      /**
       * Scenarios excluded by `@wip` / `tracked:` / similar tags.
       */
      skipped: number;
      status: Status;
      /**
       * Total scenarios across all .feature files.
       */
      total_scenarios: number;
      type: "BddSkipCount";
      [k: string]: unknown;
    }
  | {
      /**
       * Anchor fragment for jump-linking from the comment.
       */
      anchor: string;
      delta_text: string;
      failure_detail_md?: string | null;
      /**
       * Per-gate Check Run references. V4 stub uses an empty vec pinned to mokumo#770; V5 populates with real runs.
       */
      gate_runs: GateRun[];
      /**
       * Stable row id (e.g. `"coverage"`). Used by the renderer for anchors.
       */
      id: string;
      /**
       * Human-readable label (e.g. `"Coverage"`).
       */
      label: string;
      status: Status;
      type: "GateRuns";
      [k: string]: unknown;
    }
  | {
      /**
       * Anchor fragment for jump-linking from the comment.
       */
      anchor: string;
      delta_text: string;
      failure_detail_md?: string | null;
      /**
       * Count of `// FLAKY:` markers in the source tree.
       */
      flaky_marker_count: number;
      /**
       * Stable row id (e.g. `"coverage"`). Used by the renderer for anchors.
       */
      id: string;
      /**
       * Human-readable label (e.g. `"Coverage"`).
       */
      label: string;
      /**
       * Count of nextest retry events on the head SHA (best-effort — `0` when no retry-event JSON is supplied).
       */
      nextest_retry_events: number;
      status: Status;
      type: "FlakyPopulation";
      [k: string]: unknown;
    }
  | {
      /**
       * Anchor fragment for jump-linking from the comment.
       */
      anchor: string;
      /**
       * Signed delta vs. base branch's most recent main run. Negative means CI got faster.
       */
      delta_seconds: number;
      /**
       * Display string (e.g. `"+92.0s"` or `"-12.5s"`).
       */
      delta_text: string;
      failure_detail_md?: string | null;
      /**
       * Stable row id (e.g. `"coverage"`). Used by the renderer for anchors.
       */
      id: string;
      /**
       * Human-readable label (e.g. `"Coverage"`).
       */
      label: string;
      status: Status;
      /**
       * Cumulative CI wall-clock for this run (sum of job durations, in seconds).
       */
      total_ci_seconds: number;
      type: "CiWallClockDelta";
      [k: string]: unknown;
    }
  | {
      /**
       * Anchor fragment for jump-linking from the comment.
       */
      anchor: string;
      /**
       * One axis per handler.
       */
      axes: CoverageAxis[];
      delta_text: string;
      failure_detail_md?: string | null;
      /**
       * Stable row id (e.g. `"coverage"`). Used by the renderer for anchors.
       */
      id: string;
      /**
       * Human-readable label (e.g. `"Coverage"`).
       */
      label: string;
      status: Status;
      type: "HandlerCoverageAxis";
      [k: string]: unknown;
    }
  | {
      /**
       * Anchor fragment for jump-linking from the comment.
       */
      anchor: string;
      delta_text: string;
      failure_detail_md?: string | null;
      /**
       * Stable row id (e.g. `"coverage"`). Used by the renderer for anchors.
       */
      id: string;
      /**
       * Human-readable label (e.g. `"Coverage"`).
       */
      label: string;
      /**
       * Mermaid markdown (already wrapped in a fenced code block).
       */
      mermaid_md: string;
      /**
       * Total node count in the (possibly truncated) diagram.
       */
      node_count: number;
      status: Status;
      type: "ChangedScopeDiagram";
      [k: string]: unknown;
    };

/**
 * Top-level scorecard artifact.
 *
 * Serializes as `scorecard.json` and is the trust boundary for the renderer. The committed JSON Schema at `.config/scorecard/schema.json` (regenerated by the `emit-schema` binary) is the validator's contract.
 */
export interface Scorecard {
  /**
   * External link to the full Check Runs page on the head commit, so the comment can satisfy "every failing gate is one click away" even when more than three gates fail.
   */
  all_check_runs_url: string;
  /**
   * `true` when the producer resolved row statuses using the hardcoded [`threshold::ThresholdConfig::fallback`] thresholds because the operator `quality.toml` was absent or empty. A present-but-malformed or unreadable `quality.toml` is a loud failure (non-zero exit, no artifact written), not a silent fallback — so this flag is `true` only for the deliberate "operator hasn't tuned thresholds yet" case.
   *
   * The renderer keys off this flag to emit [`threshold::STARTER_PREAMBLE`] + [`threshold::FALLBACK_MARKER`] + [`threshold::PATH_HINT_COMMENT`] so operators can tell at a glance that the verdict came from starter-wheel defaults rather than their tuned thresholds.
   */
  fallback_thresholds_active: boolean;
  /**
   * Resolved status across all rows. The renderer's banner reads this directly; per the .feature spec the banner status is the worst status across all rows.
   */
  overall_status: Status;
  /**
   * Pull request metadata captured at producer time so the renderer can render without a separate `pr-meta.json` lookup.
   */
  pr: PrMeta;
  /**
   * Scorecard rows.
   */
  rows: Row[];
  /**
   * Schema version. Future row variants bump per the migration playbook in `decisions/mokumo/adr-scorecard-crate-shape.md`.
   */
  schema_version: number;
  /**
   * Top-failing gate Check Run links (max three per the two-click rule). May be omitted on the wire; deserialization fills `vec![]`. Producers SHOULD emit explicitly so the wire contract is unambiguous.
   */
  top_failures?: GateRun[];
  [k: string]: unknown;
}
/**
 * Pull request metadata — the renderer's identity for the sticky comment.
 */
export interface PrMeta {
  base_sha: string;
  head_sha: string;
  /**
   * Whether the PR was opened from a fork. Renderer uses this to scope Check Run links against the fork's head commit per the .feature spec.
   */
  is_fork: boolean;
  pr_number: number;
  [k: string]: unknown;
}
/**
 * Coverage drill-down breakouts shown beneath the [`Row::CoverageDelta`] summary cell. V4 ships the type with `by_crate` populated by the coverage producer; the per-handler `handlers` vec stays empty until the per-handler-branch tooling (mokumo#583) ships.
 */
export interface Breakouts {
  /**
   * Per-crate line + (eventually) per-handler-branch breakdown.
   */
  by_crate: CrateBreakout[];
  [k: string]: unknown;
}
/**
 * Per-crate breakdown entry for [`Breakouts::by_crate`].
 */
export interface CrateBreakout {
  /**
   * Crate name (e.g. `"kikan"`).
   */
  crate_name: string;
  /**
   * Per-handler branch coverage entries. Empty until the producer (mokumo#583) ships; the renderer surfaces a `(per-handler producer pending — see #583)` note inline when the vec is empty.
   */
  handlers: HandlerBreakout[];
  /**
   * Per-crate line coverage delta in percentage points vs base.
   */
  line_delta_pp: number;
  [k: string]: unknown;
}
/**
 * Per-handler branch coverage entry for the [`CoverageDelta::breakouts`] drill-down (Quinn blind-spot 3 sibling — surfaces uncovered handler negative paths inside the coverage row).
 */
export interface HandlerBreakout {
  /**
   * Branch coverage on the handler (0.0 - 100.0).
   */
  branch_coverage_pct: number;
  /**
   * Handler identifier (e.g. `"POST /api/users"`).
   */
  handler: string;
  [k: string]: unknown;
}
/**
 * One mutation that survived for the `MutationSurvivors` row's top-N.
 *
 * V4 ships the variant + supporting type. The producer (`cargo-mutants --in-diff`, mokumo#748) populates instances in a follow-up PR once the upstream gate ships; until then `top_survivors` is stub-empty.
 */
export interface MutationSurvivor {
  /**
   * Source file the surviving mutant lives in.
   */
  file: string;
  /**
   * `cargo-mutants` mutation kind label (e.g. `"replace + with -"`).
   */
  kind: string;
  /**
   * 1-based line number.
   */
  line: number;
  [k: string]: unknown;
}
/**
 * One crate's scenario × skip × tag breakdown for the `BddSkipCount` row. Absorbs the cut standalone `bdd_scenarios` row per CPO R2 — total scenario count + per-crate × module × tag-count drill-down lives here.
 */
export interface BddCrateBreakout {
  /**
   * Per-tag drill-down (counts by tag literal).
   */
  by_tag: TagCount[];
  /**
   * Crate name (e.g. `"mokumo-shop"`).
   */
  crate_name: string;
  /**
   * Scenarios skipped via `@wip` / `tracked:` / similar tags.
   */
  skipped: number;
  /**
   * Total scenario count across the crate's `.feature` files.
   */
  total: number;
  [k: string]: unknown;
}
/**
 * Per-tag breakdown inside a [`BddCrateBreakout`].
 */
export interface TagCount {
  /**
   * Number of scenarios bearing this tag in the crate.
   */
  count: number;
  /**
   * Tag literal as it appears in the .feature file (`@wip`, `tracked:mokumo#123`, ...).
   */
  tag: string;
  [k: string]: unknown;
}
/**
 * Reference to a single failing gate's Check Run, surfaced in `top_failures` for the two-click rule.
 */
export interface GateRun {
  gate_name: string;
  run_id: number;
  /**
   * Absolute https:// URL to the Check Run page.
   */
  url: string;
  [k: string]: unknown;
}
/**
 * One handler's negative-path coverage axis for the `HandlerCoverageAxis` row (Quinn blind-spot 3).
 *
 * Boolean columns mark whether a scenario for that axis exists in BDD — a `false` is the actionable signal (negative path uncovered).
 */
export interface CoverageAxis {
  /**
   * 4xx error path covered.
   */
  error_4xx: boolean;
  /**
   * 5xx error path covered.
   */
  error_5xx: boolean;
  /**
   * Handler identifier (e.g. `"POST /api/users"`).
   */
  handler: string;
  /**
   * Happy path covered.
   */
  happy: boolean;
  [k: string]: unknown;
}
