// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { JsonValue } from "./serde_json/JsonValue";

/**
 * API response DTO for an activity log entry.
 */
export type ActivityEntryResponse = {
  id: number;
  entity_type: string;
  entity_id: string;
  action: string;
  actor_id: string;
  actor_type: string;
  payload: JsonValue | null;
  created_at: string;
};
