// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type AppDiagnostics = {
  name: string;
  version: string;
  build_commit: string;
};
