// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * A single pre-migration backup entry for a database profile.
 */
export type BackupEntry = {
  /**
   * Absolute path to the backup file on disk.
   */
  path: string;
  /**
   * Migration version string the backup was taken at (e.g. `"m20260404_000000_set_pragmas"`).
   */
  version: string;
  /**
   * RFC 3339 timestamp from the backup file's mtime (best-effort).
   */
  backed_up_at: string;
};
