// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ProfileBackups } from "./ProfileBackups";

/**
 * Response from `GET /api/backup-status`.
 */
export type BackupStatusResponse = {
  production: ProfileBackups;
  demo: ProfileBackups;
};
