// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * API response DTO for a customer record.
 *
 * The `id` field is a String (UUID as text for JSON). Mapping from
 * `core::Customer` happens in the API layer via `From` impl.
 */
export type CustomerResponse = {
  id: string;
  company_name: string | null;
  display_name: string;
  email: string | null;
  phone: string | null;
  address_line1: string | null;
  address_line2: string | null;
  city: string | null;
  state: string | null;
  postal_code: string | null;
  country: string | null;
  notes: string | null;
  portal_enabled: boolean;
  portal_user_id: string | null;
  tax_exempt: boolean;
  tax_exemption_certificate_path: string | null;
  tax_exemption_expires_at: string | null;
  payment_terms: string | null;
  credit_limit_cents: number | null;
  stripe_customer_id: string | null;
  quickbooks_customer_id: string | null;
  lead_source: string | null;
  tags: string | null;
  created_at: string;
  updated_at: string;
  deleted_at: string | null;
};
