// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { AppDiagnostics } from "./AppDiagnostics";
import type { DatabaseDiagnostics } from "./DatabaseDiagnostics";
import type { OsDiagnostics } from "./OsDiagnostics";
import type { RuntimeDiagnostics } from "./RuntimeDiagnostics";
import type { SystemDiagnostics } from "./SystemDiagnostics";

export type DiagnosticsResponse = {
  app: AppDiagnostics;
  database: DatabaseDiagnostics;
  runtime: RuntimeDiagnostics;
  os: OsDiagnostics;
  system: SystemDiagnostics;
};
