// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Machine-readable error code for API responses.
 *
 * Serializes to snake_case strings (e.g. `NotFound` → `"not_found"`),
 * keeping the wire format unchanged from the previous `String` representation.
 * Both Rust and generated TypeScript get exhaustive matching.
 */
export type ErrorCode =
  | "not_found"
  | "conflict"
  | "validation_error"
  | "internal_error"
  | "parse_error"
  | "network_error"
  | "invalid_credentials"
  | "unauthorized"
  | "forbidden"
  | "invalid_token"
  | "setup_failed"
  | "rate_limited"
  | "method_not_allowed"
  | "production_db_exists"
  | "not_mokumo_database"
  | "database_corrupt"
  | "schema_incompatible"
  | "restore_in_progress"
  | "shop_logo_requires_production_profile"
  | "logo_format_unsupported"
  | "logo_too_large"
  | "logo_dimensions_exceeded"
  | "logo_malformed"
  | "missing_field"
  | "shop_logo_not_found"
  | "demo_setup_required";
