// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Wire format for API error responses.
 *
 * Every non-2xx response from the API returns this shape.
 * `details` carries per-field validation messages when present.
 */
export type ErrorBody = {
  code: string;
  message: string;
  details: { [key in string]?: Array<string> } | null;
};
