// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { BackupEntry } from "./BackupEntry";

/**
 * All backup entries for a single database profile (production or demo).
 */
export type ProfileBackups = {
  /**
   * Newest backup first.
   */
  backups: Array<BackupEntry>;
};
