// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type ProfileDbDiagnostics = {
  schema_version: number;
  file_size_bytes: number | null;
  wal_mode: boolean;
  /**
   * Write-ahead log size in bytes; 0 when no WAL file exists.
   */
  wal_size_bytes: number;
  /**
   * True when the freelist exceeds 20 % of total pages (VACUUM advisable).
   */
  vacuum_needed: boolean;
};
