// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type ServerInfoResponse = {
  lan_url: string | null;
  ip_url: string | null;
  mdns_active: boolean;
  host: string;
  port: number;
};
