// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type SetupStatusResponse = {
  setup_complete: boolean;
  setup_mode: "demo" | "production" | null;
};
