// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type SystemDiagnostics = {
  hostname: string | null;
  total_memory_bytes: number;
  used_memory_bytes: number;
  disk_total_bytes: number;
  disk_free_bytes: number;
};
