// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * A single applied migration.
 */
export type AppliedMigration = {
  graft_id: string;
  name: string;
  /**
   * Unix timestamp (seconds since epoch) when the migration was applied.
   */
  applied_at: bigint;
};
