// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Request body for `POST /backups/create`.
 */
export type BackupCreateRequest = {
  /**
   * Profile to back up. Defaults to the active profile if omitted.
   */
  profile: "demo" | "production" | null;
};
