// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Response from `POST /backups/create`.
 */
export type BackupCreatedResponse = {
  path: string;
  size: bigint;
  profile: "demo" | "production";
};
