// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Machine-readable error code for API responses.
 *
 * Serializes to snake_case strings (e.g. `NotFound` → `"not_found"`),
 * keeping the wire format unchanged from the previous `String` representation.
 * Both Rust and generated TypeScript get exhaustive matching.
 *
 * **Platform-only.** Shop-vertical codes live in
 * `mokumo-shop::types::error::ShopErrorCode`.
 */
export type ErrorCode =
  | "not_found"
  | "conflict"
  | "validation_error"
  | "internal_error"
  | "parse_error"
  | "network_error"
  | "invalid_credentials"
  | "unauthorized"
  | "forbidden"
  | "invalid_token"
  | "setup_failed"
  | "rate_limited"
  | "method_not_allowed"
  | "production_db_exists"
  | "not_mokumo_database"
  | "database_corrupt"
  | "schema_incompatible"
  | "restore_in_progress"
  | "demo_setup_required"
  | "account_locked"
  | "already_bootstrapped";
