// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Response from `GET /api/kikan-version`.
 *
 * Returned unauthenticated so the admin SPA can compare its baked-in
 * `api_version` against the live engine before the login page renders.
 * On mismatch, the SPA surfaces a non-blocking banner; on match, no UI.
 */
export type KikanVersionResponse = {
  /**
   * Semver of the HTTP API contract. The admin SPA bakes this value
   * at build time and compares to the live response.
   */
  api_version: string;
  /**
   * Semver of the running `kikan` crate (from `CARGO_PKG_VERSION`).
   */
  engine_version: string;
  /**
   * Short git SHA baked in at build time via `build.rs`. `"unknown"`
   * when the engine was built outside a git tree.
   */
  engine_commit: string;
  /**
   * Applied-migration name per database, keyed by the profile directory
   * name the graft declared (e.g. `"demo"`, `"production"`). Value is
   * the highest `seaql_migrations.version` for that pool, or the empty
   * string when the pool has no migrations applied.
   */
  schema_versions: Record<string, string>;
};
