// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ProfileMigrationStatus } from "./ProfileMigrationStatus";

/**
 * Response from `GET /migrate/status`.
 */
export type MigrationStatusResponse = {
  production: ProfileMigrationStatus;
  demo: ProfileMigrationStatus;
};
