// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ProfileInfo } from "./ProfileInfo";

/**
 * Response from `GET /profiles`.
 */
export type ProfileListResponse = {
  profiles: Array<ProfileInfo>;
  active: "demo" | "production";
};
