// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { AppliedMigration } from "./AppliedMigration";

/**
 * Migration status for a single profile.
 */
export type ProfileMigrationStatus = {
  applied: Array<AppliedMigration>;
  schema_version: bigint;
};
