// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Response from `POST /profiles/switch`.
 */
export type ProfileSwitchAdminResponse = {
  previous: "demo" | "production";
  current: "demo" | "production";
};
