// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Status of a single profile (demo or production).
 */
export type ProfileInfo = {
  name: "demo" | "production";
  active: boolean;
  /**
   * `PRAGMA user_version` value, or 0 if the database is not initialized.
   */
  schema_version: bigint;
  /**
   * Database file size in bytes, or `None` if the file does not exist.
   */
  file_size_bytes: bigint | null;
};
