// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Body for `POST /api/platform/v1/auth/recover/complete`.
 */
export type RecoverCompleteRequest = {
  recovery_session_id: string;
  pin: string;
  new_password: string;
};
