// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Body for `POST /api/platform/v1/auth/recover/request`.
 *
 * Identifies the account by email; the server mints a high-entropy
 * `recovery_session_id` (returned in the response) plus a 6-digit PIN
 * the operator reads from a vertical-supplied recovery artifact.
 */
export type RecoverInitiateRequest = { email: string };
