// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Response shape for `POST /api/platform/v1/auth/recover/complete`.
 */
export type RecoverCompleteResponse = { message: string };
