// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Response shape for `POST /api/platform/v1/auth/recover/request`.
 *
 * `recovery_session_id` is opaque high-entropy hex (256 bits) and is
 * always returned regardless of whether `email` matched a known
 * account (anti-enumeration). `recovery_file_path` is the operator-
 * readable artifact location the vertical produced; `None` for
 * verticals that deliver the PIN out-of-band.
 */
export type RecoverInitiateResponse = {
  recovery_session_id: string;
  recovery_file_path: string | null;
};
