// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ShopErrorCode } from "./ShopErrorCode";

/**
 * Shop-vertical wire shape mirroring `kikan_types::error::ErrorBody` but
 * keyed by `ShopErrorCode`. Serializes to byte-identical JSON when the code
 * strings match, so Hurl smoke tests see no difference.
 */
export type ShopErrorBody = {
  code: ShopErrorCode;
  message: string;
  details: { [key in string]: Array<string> } | null;
};
