// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Shop-vertical machine-readable error code for API responses.
 *
 * Serializes to snake_case strings (e.g. `LogoTooLarge` → `"logo_too_large"`),
 * preserving the historical wire format byte-for-byte.
 */
export type ShopErrorCode =
  | "shop_logo_requires_production_profile"
  | "logo_format_unsupported"
  | "logo_too_large"
  | "logo_dimensions_exceeded"
  | "logo_malformed"
  | "missing_field"
  | "shop_logo_not_found";
