//! Recovery-session storage for the file-drop password-reset flow.
//!
//! `recover_request` mints a [`RecoverySessionId`] (32-byte hex), hashes
//! the operator-facing PIN, and inserts a [`PendingReset`] keyed by the
//! session id into [`crate::PlatformState::reset_pins`]. The session id
//! is returned to the caller; the PIN is written to the operator-visible
//! recovery artifact via the recovery-writer closure installed at boot
//! through [`crate::BootConfig::with_recovery_writer`].
//!
//! Single-tenant lookup is by session id, never by email. The user-facing
//! secret is the 6-digit PIN; the session id is an opaque high-entropy
//! token the SPA carries between `recover/request` and `recover/complete`.
//! Anti-enumeration on `recover/request` synthesises a fake session id
//! for unknown emails so the response shape is uniform.
//!
//! Eviction has two layers:
//!
//! 1. **Lazy** — `recover_complete` calls `DashMap::remove(&session_id)`
//!    as the atomic consume. An expired entry returned by `remove` is
//!    discarded by the elapsed-time check in the pure-fn layer; the
//!    record is gone in either case (one-shot by construction).
//! 2. **Background sweep** — see [`super::sweep`]. Bounds memory at
//!    `~PIN_EXPIRY × issuance_rate` for sessions never redeemed by the
//!    operator.

use std::time::SystemTime;

use crate::auth::UserId;

/// Maximum incorrect PIN submissions per session before the record is
/// evicted. The pure-fn layer atomic-removes the record on bad PIN,
/// increments, and re-inserts only while `attempts < MAX_PIN_ATTEMPTS`.
pub const MAX_PIN_ATTEMPTS: u8 = 3;

/// Hard expiry on a pending reset record. After this elapses the record
/// is treated as gone regardless of attempt count.
pub const PIN_EXPIRY: std::time::Duration = std::time::Duration::from_secs(15 * 60);

/// Opaque high-entropy token bound to a single recovery flow.
///
/// 64 hex chars (256 bits) generated by [`RecoverySessionId::generate`]
/// using `rand::rng()`. Treated as a string by callers; the only
/// invariant the engine relies on is that it round-trips through
/// `Display`/`FromStr` for wire transport. Equality and hashing follow
/// the inner string.
#[derive(Debug, Clone, PartialEq, Eq, Hash)]
pub struct RecoverySessionId(String);

impl RecoverySessionId {
    /// Mint a fresh session id from 32 random bytes (256 bits) rendered
    /// as lowercase hex.
    pub fn generate() -> Self {
        use rand::Rng;
        let mut rng = rand::rng();
        let mut bytes = [0u8; 32];
        rng.fill_bytes(&mut bytes);
        let mut hex = String::with_capacity(64);
        for byte in bytes {
            hex.push_str(&format!("{byte:02x}"));
        }
        Self(hex)
    }

    /// Borrow the inner hex string for wire transport / DashMap lookup.
    pub fn as_str(&self) -> &str {
        &self.0
    }

    /// Consume into the inner string.
    pub fn into_string(self) -> String {
        self.0
    }
}

impl From<String> for RecoverySessionId {
    fn from(s: String) -> Self {
        Self(s)
    }
}

impl std::fmt::Display for RecoverySessionId {
    fn fmt(&self, f: &mut std::fmt::Formatter<'_>) -> std::fmt::Result {
        f.write_str(&self.0)
    }
}

/// In-memory recovery-session record. Stored in
/// [`crate::PlatformState::reset_pins`] keyed by [`RecoverySessionId`].
///
/// `attempts` is incremented atomically by the pure-fn layer (which
/// uses `DashMap::remove → modify → reinsert` so the increment cannot
/// race with another concurrent submission). Records are dropped at
/// `attempts >= MAX_PIN_ATTEMPTS` and on successful redemption.
#[derive(Debug, Clone)]
pub struct PendingReset {
    /// Argon2id hash of the 6-digit PIN. Constant-time compare via
    /// `password_auth::verify_password`.
    pub pin_hash: String,
    /// User this record was minted for. Bound at request time so
    /// `recover_complete` does not need to re-resolve the email.
    pub user_id: UserId,
    /// Monotonic-ish wall-clock instant the session was issued. The
    /// elapsed-time check uses `SystemTime::elapsed`, which clamps
    /// negative deltas (clock skew) to zero — i.e. a backwards clock
    /// jump never extends a session beyond `PIN_EXPIRY`.
    pub created_at: SystemTime,
    /// Incorrect-PIN counter. Eviction trigger at `MAX_PIN_ATTEMPTS`.
    pub attempts: u8,
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn generated_session_id_is_64_hex_chars() {
        let id = RecoverySessionId::generate();
        assert_eq!(id.as_str().len(), 64);
        assert!(id.as_str().chars().all(|c| c.is_ascii_hexdigit()));
    }

    #[test]
    fn two_generated_session_ids_differ() {
        let a = RecoverySessionId::generate();
        let b = RecoverySessionId::generate();
        assert_ne!(a, b, "256 bits of entropy should not collide in practice");
    }
}
