//! Render a [`HandlerScenarioArtifact`] as a markdown summary.
//!
//! Layout:
//!
//! ```text
//! # Handler ↔ Scenario Map
//! Generated: ...
//! Rows consumed: 1234
//!
//! ## <crate-name>
//! | Method | Path                | Happy | 4xx | 5xx |
//! |--------|---------------------|------:|----:|----:|
//! | GET    | `/api/customers`    |     5 |   2 |   — |
//! | ...
//!
//! ## Diagnostics
//! ...
//!
//! ## Per-handler scenario detail
//! Collapsible appendix listing the actual scenario names per handler.
//! ```

use std::fmt::Write;

use super::artifact::HandlerScenarioArtifact;

const HEADER_PREFIX: &str = "# Handler ↔ Scenario Map\n\n";
const FOOTER: &str = "_Generated by `cargo run -p docs-gen --bin handler-scenario-coverage` — see\
     [ops/standards/testing.md §Handler ↔ scenario traceability](./ops/standards/testing.md)._\n";

#[must_use]
pub fn render(artifact: &HandlerScenarioArtifact) -> String {
    let mut out = String::new();
    out.push_str(HEADER_PREFIX);
    let _ = writeln!(
        out,
        "Generated: `{}` · rows consumed: `{}`\n",
        artifact.generated_at, artifact.diagnostics.rows_consumed
    );
    out.push_str(
        "Each row is a `(method, path)` declared in a `Router::route(..)` chain. \
         Columns count distinct **scenario names** that hit the route at least once \
         with a 2xx, 4xx, or 5xx response. The fail-closed gate currently requires \
         **happy + 4xx** for new handlers (5xx is informational; see \
         `docs/adr/adr-handler-scenario-coverage.md`).\n\n",
    );

    for crate_block in &artifact.by_crate {
        let _ = writeln!(out, "## `{}`\n", crate_block.crate_name);
        if crate_block.handlers.is_empty() {
            out.push_str("_(no handlers walked)_\n\n");
            continue;
        }
        out.push_str("| Method | Path | Happy | 4xx | 5xx |\n");
        out.push_str("|--------|------|------:|----:|----:|\n");
        for h in &crate_block.handlers {
            let _ = writeln!(
                out,
                "| {} | `{}` | {} | {} | {} |",
                h.method,
                h.path,
                fmt_count(h.happy.len()),
                fmt_count(h.error_4xx.len()),
                fmt_count(h.error_5xx.len()),
            );
        }
        out.push('\n');
    }

    render_diagnostics(artifact, &mut out);
    render_appendix(artifact, &mut out);

    out.push_str(FOOTER);
    out
}

fn fmt_count(n: usize) -> String {
    if n == 0 { "—".into() } else { n.to_string() }
}

fn render_diagnostics(artifact: &HandlerScenarioArtifact, out: &mut String) {
    let d = &artifact.diagnostics;
    if d.unresolvable_routes.is_empty()
        && d.orphan_observations.is_empty()
        && d.jsonl_errors.is_empty()
        && d.excluded_crates.is_empty()
    {
        return;
    }
    out.push_str("## Diagnostics\n\n");
    render_excluded_crates(d, out);
    render_unresolvable_routes(d, out);
    render_orphan_observations(d, out);
    render_jsonl_errors(d, out);
}

fn render_excluded_crates(d: &super::artifact::Diagnostics, out: &mut String) {
    if d.excluded_crates.is_empty() {
        return;
    }
    let _ = writeln!(
        out,
        "**Excluded crates** (per `crap4rs.toml`): {}\n",
        d.excluded_crates.join(", ")
    );
}

fn render_unresolvable_routes(d: &super::artifact::Diagnostics, out: &mut String) {
    if d.unresolvable_routes.is_empty() {
        return;
    }
    out.push_str("### Unresolvable routes\n\n");
    for u in &d.unresolvable_routes {
        let _ = writeln!(
            out,
            "- `{}` at `{}:{}` — {}",
            u.route_literal, u.source_file, u.source_line, u.reason
        );
    }
    out.push('\n');
}

fn render_orphan_observations(d: &super::artifact::Diagnostics, out: &mut String) {
    if d.orphan_observations.is_empty() {
        return;
    }
    out.push_str("### Orphan observations\n\n");
    out.push_str(
        "Captured rows whose `(method, matched_path)` does not match any walked route. \
         Usually means a stale test fixture, a removed handler, or a path the walker \
         couldn't resolve.\n\n",
    );
    for o in &d.orphan_observations {
        let examples = if o.example_scenarios.is_empty() {
            String::new()
        } else {
            format!(" — e.g. {}", o.example_scenarios.join("; "))
        };
        let _ = writeln!(out, "- `{} {}`{}", o.method, o.matched_path, examples);
    }
    out.push('\n');
}

fn render_jsonl_errors(d: &super::artifact::Diagnostics, out: &mut String) {
    if d.jsonl_errors.is_empty() {
        return;
    }
    out.push_str("### JSONL parse errors\n\n");
    for e in &d.jsonl_errors {
        let _ = writeln!(out, "- `{}:{}` — {}", e.file, e.line, e.reason);
    }
    out.push('\n');
}

fn render_appendix(artifact: &HandlerScenarioArtifact, out: &mut String) {
    out.push_str("## Per-handler scenario detail\n\n");
    let mut any = false;
    for crate_block in &artifact.by_crate {
        for h in &crate_block.handlers {
            if h.happy.is_empty() && h.error_4xx.is_empty() && h.error_5xx.is_empty() {
                continue;
            }
            any = true;
            let _ = writeln!(
                out,
                "### `{} {}` ({})",
                h.method, h.path, crate_block.crate_name
            );
            render_bucket(out, "Happy", &h.happy);
            render_bucket(out, "4xx", &h.error_4xx);
            render_bucket(out, "5xx", &h.error_5xx);
            out.push('\n');
        }
    }
    if !any {
        out.push_str("_(no covered handlers — capture stream may be empty)_\n\n");
    }
}

fn render_bucket(out: &mut String, label: &str, scenarios: &[String]) {
    if scenarios.is_empty() {
        return;
    }
    let _ = writeln!(out, "- **{label}**:");
    for s in scenarios {
        let _ = writeln!(out, "  - {s}");
    }
}

#[cfg(test)]
mod tests {
    use super::*;
    use crate::scenario_coverage::artifact::*;

    fn handler(
        method: &str,
        path: &str,
        happy: &[&str],
        err4: &[&str],
        err5: &[&str],
    ) -> HandlerEntry {
        HandlerEntry {
            method: method.into(),
            path: path.into(),
            rust_path: format!("crate::{path}"),
            source_file: "crates/x/src/lib.rs".into(),
            source_line: 1,
            happy: happy.iter().map(|s| (*s).into()).collect(),
            error_4xx: err4.iter().map(|s| (*s).into()).collect(),
            error_5xx: err5.iter().map(|s| (*s).into()).collect(),
        }
    }

    #[test]
    fn renders_table_per_crate() {
        let artifact = HandlerScenarioArtifact {
            version: 1,
            generated_at: "2026-05-06T00:00:00Z".into(),
            by_crate: vec![CrateHandlers {
                crate_name: "mokumo-shop".into(),
                handlers: vec![
                    handler("GET", "/api/customers", &["list returns all"], &[], &[]),
                    handler(
                        "POST",
                        "/api/customers",
                        &["creation accepted"],
                        &["rejects invalid"],
                        &[],
                    ),
                ],
            }],
            diagnostics: Diagnostics::default(),
        };
        let md = render(&artifact);
        assert!(md.contains("# Handler ↔ Scenario Map"));
        assert!(md.contains("| GET | `/api/customers` | 1 | — | — |"));
        assert!(md.contains("| POST | `/api/customers` | 1 | 1 | — |"));
        assert!(md.contains("### `GET /api/customers` (mokumo-shop)"));
    }

    #[test]
    fn omits_diagnostics_section_when_clean() {
        let artifact = HandlerScenarioArtifact {
            version: 1,
            generated_at: "x".into(),
            by_crate: Vec::new(),
            diagnostics: Diagnostics::default(),
        };
        let md = render(&artifact);
        assert!(!md.contains("## Diagnostics"));
    }

    #[test]
    fn renders_orphan_observations() {
        let mut diagnostics = Diagnostics::default();
        diagnostics.orphan_observations.push(OrphanObservation {
            method: "GET".into(),
            matched_path: "/api/missing".into(),
            example_scenarios: vec!["dangling".into()],
        });
        let artifact = HandlerScenarioArtifact {
            version: 1,
            generated_at: "x".into(),
            by_crate: Vec::new(),
            diagnostics,
        };
        let md = render(&artifact);
        assert!(md.contains("Orphan observations"));
        assert!(md.contains("`GET /api/missing`"));
        assert!(md.contains("dangling"));
    }

    #[test]
    fn renders_unresolvable_routes() {
        let mut diagnostics = Diagnostics::default();
        diagnostics.unresolvable_routes.push(UnresolvableRoute {
            route_literal: "/api/dynamic".into(),
            source_file: "crates/x/src/lib.rs".into(),
            source_line: 42,
            reason: "non-literal path expression".into(),
        });
        let artifact = HandlerScenarioArtifact {
            version: 1,
            generated_at: "x".into(),
            by_crate: Vec::new(),
            diagnostics,
        };
        let md = render(&artifact);
        assert!(md.contains("### Unresolvable routes"));
        assert!(md.contains("`/api/dynamic`"));
        assert!(md.contains("crates/x/src/lib.rs:42"));
        assert!(md.contains("non-literal path expression"));
    }

    #[test]
    fn renders_excluded_crates() {
        let diagnostics = Diagnostics {
            excluded_crates: vec!["mokumo-desktop".into(), "kikan-tauri".into()],
            ..Diagnostics::default()
        };
        let artifact = HandlerScenarioArtifact {
            version: 1,
            generated_at: "x".into(),
            by_crate: Vec::new(),
            diagnostics,
        };
        let md = render(&artifact);
        assert!(md.contains("**Excluded crates**"));
        assert!(md.contains("mokumo-desktop, kikan-tauri"));
    }

    #[test]
    fn renders_jsonl_errors() {
        let mut diagnostics = Diagnostics::default();
        diagnostics.jsonl_errors.push(JsonlError {
            file: "target/bdd-coverage/api_bdd-1.jsonl".into(),
            line: 7,
            reason: "parse: missing field `scenario`".into(),
        });
        let artifact = HandlerScenarioArtifact {
            version: 1,
            generated_at: "x".into(),
            by_crate: Vec::new(),
            diagnostics,
        };
        let md = render(&artifact);
        assert!(md.contains("### JSONL parse errors"));
        assert!(md.contains("api_bdd-1.jsonl"));
        assert!(md.contains("missing field"));
    }

    #[test]
    fn orphan_observation_with_no_examples_omits_suffix() {
        let mut diagnostics = Diagnostics::default();
        diagnostics.orphan_observations.push(OrphanObservation {
            method: "GET".into(),
            matched_path: "/api/missing".into(),
            example_scenarios: Vec::new(),
        });
        let artifact = HandlerScenarioArtifact {
            version: 1,
            generated_at: "x".into(),
            by_crate: Vec::new(),
            diagnostics,
        };
        let md = render(&artifact);
        assert!(md.contains("`GET /api/missing`"));
        assert!(!md.contains("e.g."));
    }

    #[test]
    fn empty_crate_block_renders_placeholder() {
        let artifact = HandlerScenarioArtifact {
            version: 1,
            generated_at: "x".into(),
            by_crate: vec![CrateHandlers {
                crate_name: "empty-crate".into(),
                handlers: Vec::new(),
            }],
            diagnostics: Diagnostics::default(),
        };
        let md = render(&artifact);
        assert!(md.contains("`empty-crate`"));
        assert!(md.contains("_(no handlers walked)_"));
    }

    #[test]
    fn appendix_falls_back_when_no_handlers_covered() {
        let artifact = HandlerScenarioArtifact {
            version: 1,
            generated_at: "x".into(),
            by_crate: vec![CrateHandlers {
                crate_name: "x".into(),
                handlers: vec![handler("GET", "/api/x", &[], &[], &[])],
            }],
            diagnostics: Diagnostics::default(),
        };
        let md = render(&artifact);
        assert!(md.contains("_(no covered handlers"));
    }
}
