//! Render a [`PubApiAuditArtifact`] as a markdown summary.
//!
//! Layout mirrors `scenario_coverage::markdown` for consistency:
//! - Per-crate header with a covered/uncovered count
//! - Collapsible `<details>` block listing each uncovered pub item with
//!   its source-file:line and kind
//! - Diagnostics section (excluded crates, parse errors, lcov errors)

use std::fmt::Write;

use super::artifact::{Diagnostics, PubApiAuditArtifact};

const HEADER: &str = "# Public-API Spec Audit\n\n";
const FOOTER: &str = "_Generated by `cargo run -p docs-gen --bin pub-api-spec-audit` — see\
     [docs/adr/adr-pub-api-spec-audit.md](./docs/adr/adr-pub-api-spec-audit.md)._\n";

#[must_use]
pub fn render(artifact: &PubApiAuditArtifact) -> String {
    let mut out = String::new();
    out.push_str(HEADER);
    let _ = writeln!(
        out,
        "Generated: `{}` · items walked: `{}` · lcov files consumed: `{}`\n",
        artifact.generated_at,
        artifact.diagnostics.items_walked,
        artifact.diagnostics.lcov_files_consumed,
    );
    out.push_str(
        "Each row is a `pub` item declared in workspace source. \"BDD-covered\" \
         means at least one source line in the item's span has lcov hit ≥ 1 from \
         a cucumber-driven test binary. Posture: fail-closed for *new* uncovered \
         items; existing items are baselined per-crate (`.config/pub-api-spec-audit/<crate>.txt`).\n\n",
    );

    for crate_block in &artifact.by_crate {
        render_crate_block(crate_block, &mut out);
    }

    render_diagnostics(&artifact.diagnostics, &mut out);
    out.push_str(FOOTER);
    out
}

fn render_crate_block(block: &super::artifact::CratePubItems, out: &mut String) {
    let total = block.items.len();
    let covered = block.items.iter().filter(|i| i.is_bdd_covered()).count();
    let uncovered = total - covered;
    let _ = writeln!(
        out,
        "## `{}` — {covered}/{total} covered ({uncovered} uncovered)\n",
        block.crate_name
    );
    if uncovered == 0 {
        out.push_str("_(every pub item exercised by ≥ 1 BDD scenario)_\n\n");
        return;
    }
    out.push_str("<details><summary>Uncovered pub items</summary>\n\n");
    out.push_str("| Item | Kind | Source |\n");
    out.push_str("|------|------|--------|\n");
    for item in block.items.iter().filter(|i| !i.is_bdd_covered()) {
        let _ = writeln!(
            out,
            "| `{}` | {} | `{}:{}` |",
            item.item_path, item.kind, item.source_file, item.source_line_start
        );
    }
    out.push_str("\n</details>\n\n");
}

fn render_diagnostics(d: &Diagnostics, out: &mut String) {
    if d.excluded_crates.is_empty() && d.parse_errors.is_empty() && d.lcov_errors.is_empty() {
        return;
    }
    out.push_str("## Diagnostics\n\n");
    render_excluded_crates(d, out);
    render_parse_errors(d, out);
    render_lcov_errors(d, out);
}

fn render_excluded_crates(d: &Diagnostics, out: &mut String) {
    if d.excluded_crates.is_empty() {
        return;
    }
    let _ = writeln!(
        out,
        "**Excluded crates** (per `crap4rs.toml`): {}\n",
        d.excluded_crates.join(", ")
    );
}

fn render_parse_errors(d: &Diagnostics, out: &mut String) {
    if d.parse_errors.is_empty() {
        return;
    }
    out.push_str("### Source parse errors\n\n");
    for e in &d.parse_errors {
        let _ = writeln!(out, "- `{}` — {}", e.file, e.reason);
    }
    out.push('\n');
}

fn render_lcov_errors(d: &Diagnostics, out: &mut String) {
    if d.lcov_errors.is_empty() {
        return;
    }
    out.push_str("### Lcov parse errors\n\n");
    for e in &d.lcov_errors {
        let _ = writeln!(out, "- `{}` — {}", e.file, e.reason);
    }
    out.push('\n');
}

#[cfg(test)]
mod tests {
    use super::*;
    use crate::pub_api_audit::artifact::{
        CratePubItems, Diagnostics, LcovError, ParseError, PubItemEntry,
    };

    fn entry(path: &str, kind: &str, covered: u32, total: u32) -> PubItemEntry {
        PubItemEntry {
            item_path: path.into(),
            kind: kind.into(),
            source_file: "crates/x/src/lib.rs".into(),
            source_line_start: 10,
            source_line_end: 20,
            bdd_covered_lines: covered,
            bdd_total_lines: total,
        }
    }

    #[test]
    fn renders_header_and_footer() {
        let artifact = PubApiAuditArtifact {
            version: 1,
            generated_at: "2026-05-06T00:00:00Z".into(),
            by_crate: Vec::new(),
            diagnostics: Diagnostics::default(),
        };
        let md = render(&artifact);
        assert!(md.starts_with("# Public-API Spec Audit"));
        assert!(md.contains("Generated: `2026-05-06T00:00:00Z`"));
        assert!(md.contains("adr-pub-api-spec-audit.md"));
    }

    #[test]
    fn renders_per_crate_covered_total_and_uncovered_table() {
        let artifact = PubApiAuditArtifact {
            version: 1,
            generated_at: "x".into(),
            by_crate: vec![CratePubItems {
                crate_name: "demo".into(),
                items: vec![
                    entry("demo::covered", "fn", 5, 5),
                    entry("demo::uncovered", "struct", 0, 5),
                ],
            }],
            diagnostics: Diagnostics::default(),
        };
        let md = render(&artifact);
        assert!(md.contains("`demo` — 1/2 covered (1 uncovered)"));
        assert!(md.contains("Uncovered pub items"));
        assert!(md.contains("`demo::uncovered`"));
        assert!(!md.contains("`demo::covered`"));
    }

    #[test]
    fn renders_full_coverage_placeholder_when_all_covered() {
        let artifact = PubApiAuditArtifact {
            version: 1,
            generated_at: "x".into(),
            by_crate: vec![CratePubItems {
                crate_name: "demo".into(),
                items: vec![entry("demo::a", "fn", 5, 5), entry("demo::b", "fn", 5, 5)],
            }],
            diagnostics: Diagnostics::default(),
        };
        let md = render(&artifact);
        assert!(md.contains("every pub item exercised by ≥ 1 BDD scenario"));
        assert!(!md.contains("Uncovered pub items"));
    }

    #[test]
    fn omits_diagnostics_section_when_clean() {
        let artifact = PubApiAuditArtifact {
            version: 1,
            generated_at: "x".into(),
            by_crate: Vec::new(),
            diagnostics: Diagnostics::default(),
        };
        let md = render(&artifact);
        assert!(!md.contains("## Diagnostics"));
    }

    #[test]
    fn renders_excluded_crates_section() {
        let artifact = PubApiAuditArtifact {
            version: 1,
            generated_at: "x".into(),
            by_crate: Vec::new(),
            diagnostics: Diagnostics {
                excluded_crates: vec!["mokumo-desktop".into(), "kikan-tauri".into()],
                ..Diagnostics::default()
            },
        };
        let md = render(&artifact);
        assert!(md.contains("**Excluded crates**"));
        assert!(md.contains("mokumo-desktop, kikan-tauri"));
    }

    #[test]
    fn renders_parse_and_lcov_error_sections() {
        let artifact = PubApiAuditArtifact {
            version: 1,
            generated_at: "x".into(),
            by_crate: Vec::new(),
            diagnostics: Diagnostics {
                parse_errors: vec![ParseError {
                    file: "crates/x/src/bad.rs".into(),
                    reason: "syn: expected ;".into(),
                }],
                lcov_errors: vec![LcovError {
                    file: "tmp/bdd.lcov".into(),
                    reason: "open: no such file".into(),
                }],
                ..Diagnostics::default()
            },
        };
        let md = render(&artifact);
        assert!(md.contains("### Source parse errors"));
        assert!(md.contains("crates/x/src/bad.rs"));
        assert!(md.contains("### Lcov parse errors"));
        assert!(md.contains("tmp/bdd.lcov"));
    }
}
